# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0border.proto\"D\n\x12\x43reateOrderRequest\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\t\x12\x19\n\x05items\x18\x02 \x03(\x0b\x32\n.OrderItem\"\'\n\x13\x43reateOrderResponse\x12\x10\n\x08order_id\x18\x01 \x01(\t\"#\n\x0fGetOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\"O\n\x10GetOrderResponse\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x19\n\x05items\x18\x03 \x03(\x0b\x32\n.OrderItem\"@\n\x18UpdateOrderStatusRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x12\n\nnew_status\x18\x02 \x01(\t\",\n\x19UpdateOrderStatusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"@\n\tOrderItem\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\r\n\x05price\x18\x03 \x01(\x01\x32\xc5\x01\n\x0cOrderService\x12\x38\n\x0b\x43reateOrder\x12\x13.CreateOrderRequest\x1a\x14.CreateOrderResponse\x12/\n\x08GetOrder\x12\x10.GetOrderRequest\x1a\x11.GetOrderResponse\x12J\n\x11UpdateOrderStatus\x12\x19.UpdateOrderStatusRequest\x1a\x1a.UpdateOrderStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CREATEORDERREQUEST']._serialized_start=15
  _globals['_CREATEORDERREQUEST']._serialized_end=83
  _globals['_CREATEORDERRESPONSE']._serialized_start=85
  _globals['_CREATEORDERRESPONSE']._serialized_end=124
  _globals['_GETORDERREQUEST']._serialized_start=126
  _globals['_GETORDERREQUEST']._serialized_end=161
  _globals['_GETORDERRESPONSE']._serialized_start=163
  _globals['_GETORDERRESPONSE']._serialized_end=242
  _globals['_UPDATEORDERSTATUSREQUEST']._serialized_start=244
  _globals['_UPDATEORDERSTATUSREQUEST']._serialized_end=308
  _globals['_UPDATEORDERSTATUSRESPONSE']._serialized_start=310
  _globals['_UPDATEORDERSTATUSRESPONSE']._serialized_end=354
  _globals['_ORDERITEM']._serialized_start=356
  _globals['_ORDERITEM']._serialized_end=420
  _globals['_ORDERSERVICE']._serialized_start=423
  _globals['_ORDERSERVICE']._serialized_end=620
# @@protoc_insertion_point(module_scope)
